# Generated by Django 4.2.2 on 2023-06-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_song_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='thumbnail',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
